package com.z.optimization.client.mixin;

import com.z.optimization.config.ZOptions;
import net.minecraft.client.Minecraft;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(Entity.class)
public class FastLerpMixin {

    // 1. Fast Body Movement (Your brilliant discovery!)
    @Inject(method = "lerpPositionAndRotationStep", at = @At("HEAD"), cancellable = true) // Added cancellable = true
    private void fastLerpBody(int stepsToTarget, double targetX, double targetY, double targetZ, double targetYRot, double targetXRot, CallbackInfo ci) {
        if (!ZOptions.fastMath) return;

        Entity entity = (Entity) (Object) this; // Using base Entity so boats and minecarts don't crash!

        if (entity.level() != null && entity.level().isClientSide()) {
            Minecraft mc = Minecraft.getInstance();
            if (mc.player != null && entity.distanceToSqr(mc.player) > (24.0 * 24.0)) {

                // Variables now perfectly match the parameters generated by your IDE!
                entity.setPos(targetX, targetY, targetZ);
                ci.cancel();
            }
        }
    }

    // 2. Fast Head Rotation
    // Added require = 0 because arrows/boats don't have heads, so Mixin might ignore this for them
    @Inject(method = "lerpHeadTo", at = @At("HEAD"), cancellable = true, require = 0)
    private void fastLerpHead(float yRot, int steps, CallbackInfo ci) {
        if (!ZOptions.fastMath) return;

        // We safely check if the entity is actually alive (zombie, player, cow) before setting head rotation
        if ((Object) this instanceof LivingEntity livingEntity) {
            if (livingEntity.level() != null && livingEntity.level().isClientSide()) {
                Minecraft mc = Minecraft.getInstance();
                if (mc.player != null && livingEntity.distanceToSqr(mc.player) > (24.0 * 24.0)) {

                    livingEntity.setYHeadRot(yRot);
                    ci.cancel();
                }
            }
        }
    }
}